# Nom du workflow affiché dans l’onglet Actions
name: Docker CI/CD Pipeline

# Déclencheur : le workflow s’exécute automatiquement à chaque push sur la branche main
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    # Machine virtuelle utilisée par GitHub
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4

      # Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build de l’image Docker
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/projet-php:latest .

      # Push de l’image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/projet-php:latest